kind: Template
apiVersion: v1
metadata:
  name: icecream-template
  annotations:
    description: icecream template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: icecream
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
    selector:
      component: icecream
      name: icecream
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: icecream
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    replicas: 1
    template:
      metadata:
        labels:
          component: icecream
          name: icecream
      spec:
        containers:
        - name: icecream
          image: akitoshka/icecream:latest
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always